USE master;
GO

IF DB_ID('TrackerDB') IS NOT NULL
BEGIN
    ALTER DATABASE TrackerDB
    SET SINGLE_USER
    WITH ROLLBACK IMMEDIATE;

    DROP DATABASE TrackerDB;
END
GO

CREATE DATABASE TrackerDB;
GO

USE TrackerDB;
GO

CREATE TABLE Users
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FNAME VARCHAR(50) NOT NULL,
    LNAME VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(15) NOT NULL
);
GO

INSERT INTO Users (FNAME, LNAME, USERNAME, PASSWORD)
VALUES ('JOHN', 'DOE', 'JOHN14', 'GH67');
GO